Revert "Use correct sdist/build_ext module"
This reverts commit 03c7346e10a0fde0532dff16c63bd8382e921e99.

Otherwise, I get this error message:
AttributeError: 'Extension' object has no attribute '_needs_stub'